### ISSUE TITLE
Markdown links do not show up.

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/eveonline-third-party-documentation#182] opened 2016-07-06 02:43 UTC
After cloning the docs and following the other commands i managed to get the live html version of the docs running locally on windows.  However the links do not show up.  Do relative links not work?

Example:

![image](https://cloud.githubusercontent.com/assets/12136995/16605951/c0d0c3ba-4301-11e6-8c97-9ec70eee9755.png)

code:

![image](https://cloud.githubusercontent.com/assets/12136995/16605966/dd6230b8-4301-11e6-9e59-a07133d3dcc5.png)

**Comment by CarbonAlabel** [comment] 2016-07-13 18:42
Can confirm that this is happening. Relative links and sidebar navigation do not work.

During the build process, these warnings are displayed for every document:
```
C:\...\eveonline-third-party-documentation\docs\index.md:7: WARNING: toctree contains reference to nonexisting document 'sso\\index'
C:\...\eveonline-third-party-documentation\docs\sso\index.md:: WARNING: document isn't included in any toctree
```

If I had to guess, the problem is in those double backslashes. No idea where they are coming from.

**Comment by JimiC** [comment] 2016-07-16 16:42
This is a known issue with recommonmark 0..4.0. Although my [PR](https://github.com/rtfd/recommonmark/pull/40) that fixed this was merged, a new version hasn't been released yet. So if you want this to work get the related `.py` file from there and replace the one on your machine. Once this is done your issue is gone.

**Closed** 2017-05-12 10:52 UTC
